version: '3.8'
services:
  fe-app:
    image: fe-container:first
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
  mysql-container:
    image: mysql
    volumes:
      - /Users/loogeek/data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: 123456
    # ports:
    #   - 3306:3306 
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/loogeek/data/redis:/data
    # ports:
    #   - 6379:6379 
    networks:
      - common-network
networks:
  common-network:
    driver: bridge